# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'weedmatch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Firebase/Auth', '~> 5.3.0'
  # Pods for weedmatch
  #pod 'React', :path => '../node_modules/react-native'
  #pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  target 'weedmatch-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
#    pod 'react-native-version-check', :path => '../node_modules/react-native-version-check'

#    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

#    pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  end

  target 'weedmatchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
